# Generated by Django 4.2.1 on 2023-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostsmodels',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_post_likes', to='users.usermodel'),
        ),
    ]
