# Generated by Django 4.2.1 on 2023-06-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContactDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_number', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_number', models.CharField(max_length=15)),
                ('student_number', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentdetailmodel',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail_contact_info', to='student.studentcontactdetailmodel'),
        ),
    ]
