# Generated by Django 4.2.1 on 2023-06-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentdetailmodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StundetPrevEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_prev_education_address', to='student.addressdetailmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_prev_education', to='student.studentdetailmodel')),
            ],
        ),
    ]
