# Generated by Django 4.2.1 on 2023-06-08 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_stundetpreveducationmodel_studentpreveducationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_education_address', to='student.addressdetailmodel')),
            ],
        ),
        migrations.AddField(
            model_name='studentdetailmodel',
            name='prev_education',
            field=models.ManyToManyField(blank=True, related_name='student_prev_education_field', to='student.preveducationmodel'),
        ),
    ]
